#!/bin/sh

# close and remove old versions
palm-launch -c net.webpresso.geotag-recorder
palm-install -r net.webpresso.geotag-recorder

# package, install and run FOSDEM app on palm emulator
palm-package contents
palm-install net.webpresso.geotag-recorder_0.0.1_all.ipk
palm-launch net.webpresso.geotag-recorder
